=== SirrealY/assignment-1--principles-of-databases--cs-365--fall-2025/xml/student.dtd
<!-- Our Root Element (Students) must contain one or more students -->
<!ELEMENT students (students+)>

<!-- A student element has child elements -->
<!ELEMENT student (firstname, middlename?, lastname, preferredname?, email, phone, standing, gpa, major, minor?, advisor, enrollmentdate, graduationdate)>

<!-- Each Student MUST have an id and a status -->
<!ATTLIST student
  id CDATA #REQUIRED
  status (full-time | part-time | graduated | withdrawn) #REQUIRED
>

<!-- Child Element Definitions -->
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT preferredname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT standing (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT enrollmentdate (#PCDATA)>
<!ELEMENT graduationdate (#PCDATA)>

=== SirrealY/assignment-1--principles-of-databases--cs-365--fall-2025/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "student.dtd">
<?xml-stylesheet type="text/css" href="style.css"?>

<students>
  <student id="1234567" status="full-time">
    <firstname>Gordon</firstname>
    <middlename>Matthew</middlename>
    <lastname>Sumner</lastname>
    <preferredname>Sting</preferredname>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
    <standing>first year</standing>
    <gpa>4.0</gpa>
    <major>Music</major>
    <minor>English</minor>
    <advisor>Andy Summers</advisor>
    <enrollmentdate>08-25-1969</enrollmentdate>
    <graduationdate>05-01-1973</graduationdate>
  </student>

  <student id="4567890" status="full-time">
    <firstname>Kim</firstname>
    <middlename></middlename>
    <lastname>Thayil</lastname>
    <preferredname></preferredname>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
    <standing>second year</standing>
    <gpa>3.0</gpa>
    <major>Philosophy</major>
    <minor>Music</minor>
    <advisor>Chris Cornell</advisor>
    <enrollmentdate>08-25-1978</enrollmentdate>
    <graduationdate>05-01-1982</graduationdate>
  </student>

  <student id="8302438" status="part-time">
    <firstname>Saul</firstname>
    <middlename></middlename>
    <lastname>Hudson</lastname>
    <preferredname>Slash</preferredname>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
    <standing>fourth year</standing>
    <gpa>2.0</gpa>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <advisor>Axl Rose</advisor>
    <enrollmentdate>08-25-1983</enrollmentdate>
    <graduationdate>05-01-1987</graduationdate>
  </student>

  <student id="2983928" status="full-time">
    <firstname>Emily</firstname>
    <middlename></middlename>
    <lastname>Kokal</lastname>
    <preferredname></preferredname>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
    <standing>third year</standing>
    <gpa>3.8</gpa>
    <major>Political Science</major>
    <minor>Law</minor>
    <advisor>Jenny Lee Lindberg</advisor>
    <enrollmentdate>08-25-1998</enrollmentdate>
    <graduationdate>05-01-2002</graduationdate>
  </student>

  <student id="7645726" status="full-time">
    <firstname>Mike</firstname>
    <middlename></middlename>
    <lastname>Inez</lastname>
    <preferredname></preferredname>
    <email>mike@aic.com</email>
    <phone>213.444.3323</phone>
    <standing>second year</standing>
    <gpa>4.0</gpa>
    <major>Business Management</major>
    <minor>Math</minor>
    <advisor>Jerry Cantrell</advisor>
    <enrollmentdate>08-25-1984</enrollmentdate>
    <graduationdate>05-01-1988</graduationdate>
  </student>
</students>
